// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'article_desc': string;
  'article_title': string;
  'row': string;
}
export const cssExports: CssExports;
export default cssExports;
