// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alarmBlock': string;
  'alarmMessage': string;
  'answer': string;
  'answerMessage': string;
  'messageBlock': string;
}
export const cssExports: CssExports;
export default cssExports;
